### ISSUE TITLE
Where is the server?

### ISSUE THREAD

**Issue by mkmik** [transparencylog/tl#16]
Hi Brandon!

The readme mentions binary.tranparencylog.net but DNS doesn't resolve that name. Should the doc be updated?

**Comment by philips** [comment]
Yes, sorry. It was moved to beta-asset.transparencylog.net as we renamed the concept from “binary transparency” to “asset transparency” which had more prior art as the term for the types of URLs we want to log:

https://en.wikipedia.org/wiki/Digital_asset
https://fedoraproject.org/wiki/Packaging%3aWeb_Assets
