### ISSUE TITLE
Installation problem: version number doesn't start with a digit in .deb package

### ISSUE THREAD

**Issue by inthenite** [transparencylog/tl#18]
I can't install tl in my debian 10 due to an error in the version number field.
I used the debian x64 .deb package.

```
$ sudo dpkg -i tl-stable-linux-amd64.deb 
dpkg: error processing archive tl-stable-linux-amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'tl':
 'Version' field value 'v0.2.6': version number does not start with digit
Errors were encountered while processing:
 tl-stable-linux-amd64.deb
```
So the 'v' has to be removed.

**Comment by philips** [comment]
I believe this is fixed now.
https://dl.equinox.io/transparencylog/tl/stable
<https://dl.equinox.io/transparencylog/tl/stable>

thank you for the bug report!
