### ISSUE TITLE
[bug] Failed to grab: file exists

### ISSUE THREAD

**Issue by developer-guy** [transparencylog/tl#29]
I'm trying the download k3sup CLI with tl but I got strange errors like the following:
```
$ tl get https://get.k3sup.dev
Failed to grab: file exists

$ tl get https://get.k3sup.dev | sh
sh: line 1: Failed: command not found
```
This is my tl CLI version:
```
$ tl version
version: 0.2.12
commit: 4c2dc0ed57ea7629988b81cb6165fe179751c56b
date: 2020-08-21T13:58:34Z
````

This is information about my environment:
```
$ uname -a
Darwin xxx 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64
```

**Comment by philips** [comment]
> tl get https://get.k3sup.dev

Can you try in a new directory? That error means tl doesn’t want to overwrite an existing file

> tl get https://get.k3sup.dev | sh

I think you want `tl cat`

**Comment by philips** [comment]
Just tested. Can you confirm you don't have a get.sh in your current working directory.

```
$ tl get https://get.k3sup.dev
fetched note: https://beta-asset.transparencylog.net/lookup/get.k3sup.dev
validated file sha256sum: 8b04eb16c6f6202e6800fb1c6ba1f8294e038472db442ac867a4a508a82c4075
Download validated and saved to get.sh
$ tl get https://get.k3sup.dev
Failed to grab: file exists
```

**Comment by developer-guy** [comment]
Thanks @philips for a quick response, yeah I tested it too, it worked thank you 👌🙏
